Rails.application.routes.draw do
  root 'homepage#index'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  post '/logout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/user' => 'users#show'
  get '/leaderboard' => 'leaderboard#index'
  get 'weekly' => 'weekly#index'
  get 'weekly/events' => 'weekly#events'
  get '/users/:id', to: 'users#others'
  post '/users/:id/approve' => 'users#approve'
  get '/users/:id/trade' => 'users#trade'
  post '/users/:id/acceptTrade' => 'users#acceptTrade'
  post '/users/declineTrade' => 'users#declineTrade'
end
